#!/bin/sh
#
maintain_device_partitions() {

# GPT partitions: as the Volumio image likely has been dd'ed to a bigger disk,
#     the backup GPT table is not at the end of the disk.
# 		Fix this before doing anything else (only at first boot)

  BOOT_DEVICE=/dev/$(lsblk -no PKNAME "${BOOT_PARTITION}")
  parted -s "${BOOT_DEVICE}" p 2>&1 | tee -a /tmp/parted
  # gpt warning
  if grep -Eq 'fix the GPT' /tmp/parted;then
    log_begin_msg "Alternate (backup) GPT header not at the end of the disk, moving it..."
    sgdisk -e "${BOOT_DEVICE}" >/dev/null 2>&1
    log_end_msg
  fi
  rm -f /tmp/parted
}
